### ISSUE TITLE
Rider support

### ISSUE THREAD

**Issue by alex6dj** [Joehaivo/icon-font-viewer#1]
Hello, I'm using .ttf fonts icons extensively in my projects, an this plugin is a good adition to my toolbox. Is Rider 2022.2 supported or will be supported, or I missing something. If not you sould consider supporting it.

**Comment by Joehaivo** [comment]
what a coincidence！I released this plugin to Jetbrain Marketplace yesterday, you can try search 'icon font viewer' in Rider Client - Plugins, it should be compatible.

**Comment by alex6dj** [comment]
Well I landed here from Jetbrain Marketplace because Rider is not supported. So yesterday... 👍 

![Captura de pantalla (6)](https://user-images.githubusercontent.com/27690651/195972702-f369653b-fe4c-40da-9942-a847199ecb04.png)

**Comment by Joehaivo** [comment]
I have uploaded a new version plugin, and Compatibility Verification Results is passed by Rider. If it still shows incompatible, you can download and install manualy.

![image](https://user-images.githubusercontent.com/12687795/196317153-e2057436-8bde-4ca1-bb7e-f7b7b6704160.png)

**Comment by alex6dj** [comment]
Installed and tested in Rider 2022.2 Build #RD-222.3345.139. Fully supported. Thanks for the good work and fast response, and get my star ⭐
